### ISSUE TITLE
S/MIME encrypted mails are not decrypted

### ISSUE THREAD

**Issue by CFPrulez** [FAU-Inf2/SMile#1]
On some devices decrypting mails with SMileCE does not work. After opening the mail, the progress wheel appears but nothing happens. 

Workaround: Enable debugging in SMileCE. Attention: This will save the en- and decrypted mail on the SD card (can be read by all apps)! 

Stacktrace:
D/SMIME API( 2365): service result: Intent { (has extras) }
E/k9      ( 2365): Error while decoding message
E/k9      ( 2365): java.lang.RuntimeException: Not supported
E/k9      ( 2365):  at com.fsck.k9.mailstore.LocalMessageExtractor.extractAttachmentInfo(LocalMessageExtractor.java:554)
E/k9      ( 2365):  at com.fsck.k9.mailstore.LocalMessageExtractor.extractAttachmentInfos(LocalMessageExtractor.java:527)
E/k9      ( 2365):  at com.fsck.k9.mailstore.LocalMessageExtractor.decodeMessageForView(LocalMessageExtractor.java:466)
E/k9      ( 2365):  at com.fsck.k9.ui.message.DecodeMessageLoader.loadInBackground(DecodeMessageLoader.java:48)
E/k9      ( 2365):  at com.fsck.k9.ui.message.DecodeMessageLoader.loadInBackground(DecodeMessageLoader.java:17)
E/k9      ( 2365):  at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:296)
E/k9      ( 2365):  at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:54)
E/k9      ( 2365):  at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:42)
E/k9      ( 2365):  at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:128)
E/k9      ( 2365):  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/k9      ( 2365):  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/k9      ( 2365):  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/k9      ( 2365):  at java.lang.Thread.run(Thread.java:818)

**Comment by CFPrulez** [comment]
This error has been fixed. It works now without having debugging enabled.

SMile cannot handle encrypted attachments. Decryption of mails with attachments will fail.

**Comment by Pazu** [comment]
The problem is still evident using SMile version 2.1.2 and SMile Cryptographic Extension version 1.1.1 on my Sony Ericsson Xperia Mini ST15i running LegacyXperia 20161025 - cm-11.0. SMile fails to recognize a signed e-mail message, displaying "smime.p7s" as an attachment. A signed and encrypted message just causes the progress circle to display indefinitely.
